# Copyright 2026 The HRX Authors
#
# Licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read
  actions: read

jobs:
  llama_cpp_linux:
    name: Linux / HRX
    uses: ./.github/workflows/build_llama_cpp_linux.yml
    permissions:
      contents: read
    with:
      name: Build
      artifact_name: llama-cpp-linux-x86_64
      build_type: Release
      hrx_build_type: Release
      package_root_name: llama.cpp-install
      upload_artifact: true
      build_test_package: true
      test_artifact_name: llama-cpp-linux-x86_64-tests

  llama_cpp_release_tests:
    name: Linux / HRX release tests
    needs: llama_cpp_linux
    uses: ./.github/workflows/test_llama_cpp_release_linux.yml
    permissions:
      contents: read
      actions: read
    with:
      name: Release tests
      release_artifact_name: llama-cpp-linux-x86_64
      test_artifact_name: llama-cpp-linux-x86_64-tests
      package_root_name: llama.cpp-install
